name: Run WebdriverIO Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.8.0'

    - name: Install dependencies
      run: npm install

    - name: Run WebdriverIO Tests
      env:
        DISPLAY: ':99.0'
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        npx wdio --spec ./test/specs/addEmployee.e2e.js

