name: Run WebdriverIO Tests

# Define triggers
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.8.0]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ 22.8.0 }}

    - name: Install dependencies
      run: npm install

    - name: Run WebdriverIO Tests
      run: npx wdio --spec ./test/specs/addEmployee.e2e.js

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: wdio-results
        path: ./results
